
package elementHandlerpkg;
import java.io.Serializable;
import java.util.ArrayList;
/**
 * This mimics R's Summary command, but does not cap the number of levels. It stores each 
 * level in a SummaryLevel. Unlike R it stores only the levels that contain values, and not every level that could 
 * have a value. (I could be wrong about that, but based on their distance algorithm that appears to be what it's 
 * doing.)
 * These summaries are stored in main under main.ptList. They are either generated by the 
 * @author Laura Manuel
 */
public class Summary implements Serializable{
    private final int ptNum;
    private final ArrayList<SummaryLevel> levels;//sorted list of levels
    private static final long serialVersionUID = 1;
    /**
     * 
     * @return The patient number for the Summary. 
     */
    public int getPTNum(){
        return ptNum;
    }
    /**
     * 
     * @return An ArrayList of SummaryLevels belonging to that patient. 
     */
    public ArrayList getLevels(){
        return levels; 
    }
    public Summary(int id, ArrayList<SummaryLevel> sortedList){
        ptNum = id;
        levels = sortedList;
    }
    
}
